//
// Generated by dtk
// Translation Unit: d_a_obj_plant.cpp
//

#include "d/actor/d_a_obj_plant.h"
#include "JSystem/J3DGraphAnimator/J3DModel.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "d/d_resorce.h"
#include "m_Do/m_Do_ext.h"

static BOOL nodeCallBack(J3DNode*, int);

/* 00000078-00000098       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* p_this) {
    return ((daObjPlant_c*)p_this)->CreateHeap();
}

/* 00000098-000001E0       .text CreateHeap__12daObjPlant_cFv */
BOOL daObjPlant_c::CreateHeap() {
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes("Plant", 3);

    JUT_ASSERT(0xAA, modelData != 0);

    mpModel = mDoExt_J3DModel__create(modelData, 0, 0x11020203);
    if (mpModel == NULL) {
        return FALSE;
    }

    JUTNameTab* pNameTab = mpModel->mModelData->getJointName();
    for (int i = 0; i < mpModel->mModelData->getJointNum(); i++) {
        const char* name = pNameTab->getName(i);
        if (strcmp("joint2", name) == 0) {
            mpModel->mModelData->getJointNodePointer(i)->mCallBack = nodeCallBack;
            break;
        }
    }

    mpModel->mModelData->setHierarchy((J3DModelHierarchy*)this);

    return TRUE;
}

/* 000001E0-000002AC       .text CreateInit__12daObjPlant_cFv */
void daObjPlant_c::CreateInit() {
    /* Nonmatching */
}

/* 000002AC-00000390       .text nodeCallBack__FP7J3DNodei */
static BOOL nodeCallBack(J3DNode* node, int param_1) {
    if (!param_1) {
        J3DJoint* joint = (J3DJoint*)node;
        s32 jntNo = joint->getJntNo();
        J3DModel* model = j3dSys.getModel();
        daObjPlant_c* p_this = (daObjPlant_c*)model->getUserArea();
        if (p_this) {
            cMtx_copy(model->getAnmMtx(jntNo), *calc_mtx);
            // TODO: Incorrect index for angle: meant to be  0x408 but has 0x206
            mDoMtx_XrotM(*calc_mtx, p_this->current.angle.x);
            mDoMtx_YrotM(*calc_mtx, p_this->current.angle.y);
            mDoMtx_XrotM(*calc_mtx, -p_this->current.angle.x);
            model->setAnmMtx(jntNo, *calc_mtx);
            cMtx_copy(*calc_mtx, J3DSys::mCurrentMtx);
        }
    }
    return TRUE;
}

/* 00000390-00000410       .text set_mtx__12daObjPlant_cFv */
void daObjPlant_c::set_mtx() {
    /* Nonmatching */
}

/* 00000410-00000544       .text daObjPlant_Create__FPv */
static s32 daObjPlant_Create(void*) {
    /* Nonmatching */
}

/* 000006FC-0000072C       .text daObjPlant_Delete__FPv */
static BOOL daObjPlant_Delete(void* p_this) {
    dComIfG_resDelete(&((daObjPlant_c*)p_this)->mPhs, "Plant");
    return TRUE;
}

/* 0000072C-00000814       .text daObjPlant_Draw__FPv */
static BOOL daObjPlant_Draw(void*) {
    /* Nonmatching */
}

/* 00000814-00000A58       .text daObjPlant_Execute__FPv */
static BOOL daObjPlant_Execute(void*) {
    /* Nonmatching */
}

/* 00000A58-00000A60       .text daObjPlant_IsDelete__FPv */
static BOOL daObjPlant_IsDelete(void* p_this) {
    return TRUE;
}
