//
// Generated by dtk
// Translation Unit: d_a_obj_plant.cpp
//

#include "d/actor/d_a_obj_plant.h"
#include "JSystem/J3DGraphAnimator/J3DModel.h"
#include "JSystem/J3DGraphBase/J3DSys.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "d/d_procname.h"
#include "m_Do/m_Do_ext.h"

static dCcD_SrcCyl l_cyl_src = {
    // dCcD_SrcGObjInf
    {
        /* Flags             */ 0,
        /* SrcObjAt  Type    */ 0,
        /* SrcObjAt  Atp     */ 0,
        /* SrcObjAt  SPrm    */ 0,
        /* SrcObjTg  Type    */ AT_TYPE_ALL,
        /* SrcObjTg  SPrm    */ TG_SPRM_SET,
        /* SrcObjCo  SPrm    */ CO_SPRM_SET | CO_SPRM_IS_UNK8 | CO_SPRM_VS_UNK2,
        /* SrcGObjAt Se      */ 0,
        /* SrcGObjAt HitMark */ 0,
        /* SrcGObjAt Spl     */ 0,
        /* SrcGObjAt Mtrl    */ 0,
        /* SrcGObjAt SPrm    */ 0,
        /* SrcGObjTg Se      */ 0,
        /* SrcGObjTg HitMark */ 0,
        /* SrcGObjTg Spl     */ 0,
        /* SrcGObjTg Mtrl    */ 0,
        /* SrcGObjTg SPrm    */ G_TG_SPRM_NO_HIT_MARK,
        /* SrcGObjCo SPrm    */ 0,
    },
    // cM3dGCylS
    {
        /* Center */ 0.0f,
        0.0f,
        0.0f,
        /* Radius */ 10.0f,
        /* Height */ 80.0f,
    },
};

static BOOL nodeCallBack(J3DNode*, int);

/* 00000078-00000098       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c* p_this) {
    return ((daObjPlant_c*)p_this)->CreateHeap();
}

/* 00000098-000001E0       .text CreateHeap__12daObjPlant_cFv */
BOOL daObjPlant_c::CreateHeap() {
    int ret;
    J3DModelData* modelData = (J3DModelData*)dComIfG_getObjectRes("Plant", 3);

    JUT_ASSERT(0xAA, modelData != 0);

    mpModel = mDoExt_J3DModel__create(modelData, 0, 0x11020203);
    if (mpModel == NULL) {
        ret = FALSE;
    } else {
        JUTNameTab* pNameTab = mpModel->mModelData->getJointName();
        for (int i = 0; i < mpModel->mModelData->getJointNum(); i++) {
            const char* name = (char*)pNameTab->getName(i);
            if (strcmp("joint2", name) == 0) {
                mpModel->mModelData->getJointNodePointer(i)->mCallBack = nodeCallBack;
                break;
            }
        }
        ret = TRUE;
    }
    return TRUE;
}

/* 000001E0-000002AC       .text CreateInit__12daObjPlant_cFv */
void daObjPlant_c::CreateInit() {
    // this->cullMtx = this->mpModel->mModelData->getJointTree().getBasicMtxCalc();
    fopAcM_setCullSizeBox((fopAc_ac_c*)this, -600.0, -0.0, -600.0, 600.0, 900.0, 600.0);
    cullSizeFar = 0x3f800000;
    mStts.Init(0xff, 0xff, this);
    mCyl.Set(l_cyl_src);
    set_mtx();
}

/* 000002AC-00000390       .text nodeCallBack__FP7J3DNodei */
static BOOL nodeCallBack(J3DNode* node, int param_1) {
    if (!param_1) {
        J3DJoint* joint = (J3DJoint*)node;
        s32 jntNo = joint->getJntNo();
        J3DModel* model = j3dSys.getModel();
        daObjPlant_c* p_this = (daObjPlant_c*)model->getUserArea();
        if (p_this) {
            cMtx_copy(model->getAnmMtx(jntNo), *calc_mtx);
            // TODO: Incorrect index for angle: meant to be  0x408 but has 0x206
            mDoMtx_XrotM(*calc_mtx, p_this->current.angle.x);
            mDoMtx_YrotM(*calc_mtx, p_this->current.angle.y);
            mDoMtx_XrotM(*calc_mtx, -p_this->current.angle.x);
            model->setAnmMtx(jntNo, *calc_mtx);
            cMtx_copy(*calc_mtx, J3DSys::mCurrentMtx);
        }
    }
    return TRUE;
}

/* 00000390-00000410       .text set_mtx__12daObjPlant_cFv */
void daObjPlant_c::set_mtx() {
    /* Nonmatching */
}

/* 00000410-00000544       .text daObjPlant_Create__FPv */
static s32 daObjPlant_Create(void*) {
    return 0;
}

/* 000006FC-0000072C       .text daObjPlant_Delete__FPv */
static BOOL daObjPlant_Delete(void* p_this) {
    dComIfG_resDelete(&((daObjPlant_c*)p_this)->mPhs, "Plant");
    return TRUE;
}

/* 0000072C-00000814       .text daObjPlant_Draw__FPv */
static BOOL daObjPlant_Draw(void*) {
    return TRUE;
}

/* 00000814-00000A58       .text daObjPlant_Execute__FPv */
static BOOL daObjPlant_Execute(void*) {
    return TRUE;
}

/* 00000A58-00000A60       .text daObjPlant_IsDelete__FPv */
static BOOL daObjPlant_IsDelete(void* p_this) {
    return TRUE;
}

static actor_method_class daObj_PlantMethodTable = {
    (process_method_func)daObjPlant_Create,  (process_method_func)daObjPlant_Delete,
    (process_method_func)daObjPlant_Execute, (process_method_func)daObjPlant_IsDelete,
    (process_method_func)daObjPlant_Draw,
};

actor_process_profile_definition g_profile_Obj_Plant = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 3,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_Obj_Plant,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjPlant_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ 0x01BE,
    /* Actor SubMtd */ &daObj_PlantMethodTable,
    /* Status       */ fopAcStts_UNK40000_e | fopAcStts_NOCULLEXEC_e,
    /* Group        */ fopAc_ACTOR_e,
    /* CullType     */ fopAc_CULLBOX_4_e,
};
